spring:
  datasource:
    url: jdbc:mariadb://svc.sel3.cloudtype.app:30057/owlworld
    username: root
    password: owl12345!!
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      adjust-dates-to-context-time-zone: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher